Capstone 1 proyect
Eldonratzlaff/capstone1 pull request #1
Opened 2023-01-13 22:03 UTC by Eldonratzlaff

Internet and technology conference page

2023-01-13 23:13 UTC, Munsa1 requested changes
Hi @Eldonratzlaff, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a descriptive ReadMe file

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-14 02:21 UTC, franclobo requested changes
Hi @Eldonratzlaff, 

# ♻️ REQUIRED CHANGES ♻️ 

![soClose](https://user-images.githubusercontent.com/58642949/212441525-df64cc62-04a0-40c5-88d9-2f82bc58c07f.gif)

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Highlights

- No linter errors ✔️ 


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please 🙏🏽 edit your PR to be more descriptive with a title and a summary of the changes in the current branch and paste the link to your video 👇🏽 

| Expected | Your PR |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/212441609-b479ac0c-140e-4783-a1e9-982952b9cd99.png) | ![image](https://user-images.githubusercontent.com/58642949/212441117-8c76a011-6108-485c-9911-0d8488a76700.png) |

- May I help you?

https://user-images.githubusercontent.com/58642949/212446396-7dfc2d34-9d9b-4100-ad95-07defa7a0f06.mp4

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-14 02:21 UTC, franclobo commented on README.md
> +- [Live Demo Link](https://eldonratzlaff.github.io/capstone1/)
- [ ] Please 🙏🏽 deploy your project with GitHub and update the link for professional documentation.
- [ ] Kindly add the link of your video to match all the project requirements 👇🏽 

> Once you have finished the development of the project, you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:

> A description of the project.
> A demo of the project features (different pages and different screen sizes).
> You should also highlight some interesting piece of code or something you built that you are very proud of.

2023-01-14 02:21 UTC, franclobo commented on README.md
> +  <img src="/pict-mobile/eldonazul1.jpeg" alt="logo" width="140"  height="auto" />
- [x] Please 🙏🏽 remove the Microverse logo or replace it with your own for professional documentation.

2023-01-14 02:21 UTC, franclobo commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [x] Kindly add your acknowledgment to the author to avoid plagiarism 👇🏽 

> Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07).


> The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

2023-01-14 02:21 UTC, franclobo commented on index.html
> +         </header>
- To be similar to the original design, please 🙏🏽 correct the following things in the header: 👇🏽 
  - **For the desk version:**
  - [x] Kindly add the black navbar with the social icons as in the original design, it should be present on both pages the home page and the about page.
  - [x] Kindly add a logo accordingly with the topic of your conference page. When the user clicks on the logo it should return to the home page.
  - [ ] Kindly correct the distance between the links. The withe navbar should be present on the about page with the HOME link that allows the user to return to the home page.
  - **For the mobile version:**
  - [ ] Kindly add a hamburger button left aligned.

| Original design | Yor design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/212441869-1e30d527-dc18-4490-8dee-319c42fc28a4.png) | ![image](https://user-images.githubusercontent.com/58642949/212441910-0fce8a83-bf01-4817-a173-efcd30767f6e.png) |
![image](https://user-images.githubusercontent.com/58642949/212442313-035e2a27-1ebb-4e44-824c-3a0e873f43e0.png) | ![image](https://user-images.githubusercontent.com/58642949/212442341-6dc58ee7-1e30-4878-a608-c4144521ee17.png) |

2023-01-14 02:21 UTC, franclobo commented on index.html
> +    </section>
- To be similar to the original design please 🙏🏽 complete the required changes for this section 👇🏽 

  - [ ] Kindly add the background image with CSS.
  - [ ] Kindly use the colors, font-family and font-size described in the original design.
![image](https://user-images.githubusercontent.com/58642949/212443025-65bb6d65-c75e-4747-81a0-7461099ca12f.png)
  - [x] Kindly use the background design in the title, and add it with CSS.

| Original design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/212442642-49597208-6d74-4e33-abb0-0d1006e8e34e.png) | ![image](https://user-images.githubusercontent.com/58642949/212442675-e071b938-3e62-4503-a7d1-4f4ce6330c9c.png) |
![image](https://user-images.githubusercontent.com/58642949/212442796-8b87ba3c-8c02-4045-a900-eddb228fd9cf.png) | ![image](https://user-images.githubusercontent.com/58642949/212442739-7b5fe0f5-32d4-4d8e-9f73-736fc0de0068.png) |

2023-01-14 02:21 UTC, franclobo commented on index.html
> +</section>
- To be similar to the original design this section should contain a header, a divider, five individual articles, each with an image, title, and description, and a line of text at the bottom. Please 🙏🏽 complete the following changes required 👇🏽 

  - **Desktop version** 
  
  - [ ] Kindly use the same background design.
  - [ ] Kindly add the red line below the title.
  - [ ] Kindly use the same icons provided in the design

![image](https://user-images.githubusercontent.com/58642949/212443661-c59cf1a7-681d-4225-8214-90cd8e45f7ec.png)
   
  - [ ] Kindly add the SEE THE WHOLE PROGRAM link.
  
  - **Mobile version**

  - [ ] Kindly add the "JOIN..." button
  - [ ] The text in the mobile version is overlapping in your design, please 🙏🏽 fix it to be similar to the original design.

| Original design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/212443442-059de3ce-2036-44d5-91e8-d47331ad2e50.png) | ![image](https://user-images.githubusercontent.com/58642949/212443401-8902e4e1-e791-46d9-b1cc-2e87a2da6798.png) |
![image](https://user-images.githubusercontent.com/58642949/212443481-67db67d6-0c3f-4d3c-8400-d6a514b91d94.png) | ![image](https://user-images.githubusercontent.com/58642949/212443512-ca82be49-457d-414e-8d7b-f995ed2c5405.png) |

2023-01-14 02:21 UTC, franclobo commented on index.html
> +</section>
- [x] This section should be completed dynamically with javascript as requested, please 🙏🏽 edit it to match all the project requirements 👇🏽 

> The section "Featured speakers" should be created dynamically in JavaScript.

- Please 🙏🏽 follow the design guidelines to be similar to the original design.

- [ ] Kindly include in this section a header, a divider, and six individual articles, each with an image, title, subtitle, and description. Each article has two columns, the first with the image at the left and the second with the title, subtitle, and description.

| Original design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/212444471-6dcf4384-8974-430c-9bb1-0324d1b673b2.png) | ![image](https://user-images.githubusercontent.com/58642949/212444509-cc10f56f-27ed-4324-9be8-a3bd8abb9b3d.png) |
![image](https://user-images.githubusercontent.com/58642949/212444539-2c947cfd-621b-47b6-84dc-b3e8badd89f0.png) | ![image](https://user-images.githubusercontent.com/58642949/212444572-8cf32187-459a-4036-b47a-1356c5f0d15a.png) |

2023-01-14 02:21 UTC, franclobo commented on index.html
> +</button>
- [ ] The "More" button should be present just in the mobile version, make sure to follow the design guidelines to be similar to the original design 👇🏽 

| Original design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/212444340-32deb377-ad65-418c-8745-cdae7374b809.png) | ![image](https://user-images.githubusercontent.com/58642949/212444370-5701def5-9224-4309-a491-80e1169f8c51.png) |

2023-01-14 02:21 UTC, franclobo commented on index.html
> +</section>
- Please 🙏🏽 follow the design guidelines to be similar to the original design 👇🏽 
- [ ] For the desktop version the partners' section is on the home page, while for the mobile version, the partners' section is on the about page. Kindly add the logos of your partners.

| Original design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/212444748-b98adc86-0e71-4c7d-8871-5dfdc1030c56.png) | ![image](https://user-images.githubusercontent.com/58642949/212444783-1b145f50-5380-4c26-8b74-27afc897295d.png) |
![image](https://user-images.githubusercontent.com/58642949/212444953-fa7c2e50-0cbb-4f2b-86cc-5c3118aef2d9.png) | Your about page is incomplete |

2023-01-14 02:21 UTC, franclobo commented on index.html
> +
- [ ] Please add the footer section for both pages the desktop version and the mobile version following the design guidelines to be similar to the original design, the footer in the desktop version for the home page is white background while the mobile version is black background, besides in the mobile version the footer is on the about page with white background. 👇🏽 

| Home page | About page |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/212445165-6866c2b4-8558-433c-9e31-f5b4171211be.png) | ![image](https://user-images.githubusercontent.com/58642949/212445204-7e9bda46-a558-45a6-b8dd-46b4ebb23839.png) |
There is no footer on the home page for the mobile version | ![image](https://user-images.githubusercontent.com/58642949/212445256-eae20c6a-865c-4384-a01f-14d65f16cad6.png) |

2023-01-14 02:21 UTC, franclobo commented on about.html
> +    </header>
- [ ] Please follow the instruction above 👆🏽 that I suggested for the index.html to be similar to the original design.

2023-01-14 02:21 UTC, franclobo commented on about.html
> +    </section>
- [ ] Please 🙏🏽 follow the design guidelines to be similar to the original design 👇🏽 
  - [ ] Kindly add the background image with CSS.
  - [ ] Kindly use the colors, font-family and font-size described in the original design.
![image](https://user-images.githubusercontent.com/58642949/212443025-65bb6d65-c75e-4747-81a0-7461099ca12f.png)

| Original design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/212445484-8d5a19b4-6dd8-49fc-bd6a-79914684c450.png) | ![image](https://user-images.githubusercontent.com/58642949/212445501-d55f71fc-1c52-4651-ae74-06146eb02832.png) |
![image](https://user-images.githubusercontent.com/58642949/212445565-c3b95241-4c61-4ba9-98a8-b9dbfdca6acd.png) | ![image](https://user-images.githubusercontent.com/58642949/212445586-3c4e6d6b-b343-48a5-991c-7425ad94998f.png) |

2023-01-14 02:21 UTC, franclobo commented on about.html
> +
- [ ] Please 🙏🏽 complete the rest of the sections of the about page for the desktop version and the mobile version to be similar to the original design.

| Desktop | Mobile |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/212445738-81b55a32-8dea-4f83-93b4-786b0fa05ce2.png) | ![image](https://user-images.githubusercontent.com/58642949/212445764-72ef8d7e-dc55-4979-b14b-000550152238.png) |
![image](https://user-images.githubusercontent.com/58642949/212445786-3feeef90-6912-4ea8-9f11-7657e4f54e27.png) | ![image](https://user-images.githubusercontent.com/58642949/212445815-af99af90-5bf0-4423-96d7-0b6997a8ae68.png) ![image](https://user-images.githubusercontent.com/58642949/212445830-585bc29f-b213-4639-b436-09a3c49ea45e.png) |

2023-01-14 02:21 UTC, franclobo commented on style.css
> +}
- [ ] To have a responsive website please 🙏🏽 avoid the horizontal scroll.

2023-01-14 02:21 UTC, franclobo commented on queristyles.css
> +}
- [ ] This is not JS code. Did you want to code CSS? Please change the name of the file or put this code in the corresponding file.

2023-01-14 02:21 UTC, franclobo commented on script.js
> +}
- [ ] Please 🙏🏽  complete the Feature Speakers section dynamically you can use an array of objects with the information of the speakers, like this 👇🏽 

![image](https://user-images.githubusercontent.com/58642949/212446226-f35d360d-ba52-4ea1-b3a2-94edfacfdab3.png)

- [ ] Kindly create a function that iterates through the speakers list on window load and creates HTML elements with the data from each object, to complete this section dynamically as required.

2023-01-14 14:03 UTC, Ismailco requested changes
#### Hi @Eldonratzlaff, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![giphy](https://user-images.githubusercontent.com/25227022/169399289-510de072-42e7-419b-8c2c-da9344bdd430.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-14 14:03 UTC, Ismailco commented on README.md
> +- [Live Demo Link](https://eldonratzlaff.github.io/capstone1/)
- [x] As the previous reviewer mentioned, kindly make sure to fix your demo link as for now it's like this 👇🏼 
![Screenshot_20230114_142826](https://user-images.githubusercontent.com/25227022/212474108-c2265279-e792-4e1b-a47f-0d643bbd031e.png)

- [x] Also kindly make sure to include a link to the video presentation about your project in the README file, the video should include a showcase of your pages on desktop and mobile screens and a piece of code you are proud of making

2023-01-14 14:03 UTC, Ismailco commented on about.html
> +
- [x] As the previous reviewer mentioned kindly include the white navbar in your about page so the user has a way to navigate your website

2023-01-14 14:03 UTC, Ismailco commented on about.html
> +    </section>
- [x] Kindly make sure to finish your about page and include all the sections here, and also consider adding a mobile hamburger menu to the about page for the mobile view. as for now, your about page looks like this 👇🏼 

![Screenshot_20230114_143626](https://user-images.githubusercontent.com/25227022/212474493-b1871ba5-fe71-43f3-b2e3-1d1d649da8e3.png)

2023-01-14 14:03 UTC, Ismailco commented on index.html
> +            </nav>
- [x] As the previous reviewer mentioned kindly make sure to correct the distance between the links, so your pages look like the provided design

![Screenshot_20230114_144040](https://user-images.githubusercontent.com/25227022/212474689-d788d103-e958-452c-972b-92ff6a9f420d.png)

2023-01-14 14:03 UTC, Ismailco commented on index.html
> +</section>
- [x] Kindly make sure to use a darker background in the `Main Program` section so the text can be read easily, also make sure to align this section properly so it takes all the width of the page (this issue is because there is a horizontal overflow, kindly consider fixing this)

![Screenshot_20230114_144501](https://user-images.githubusercontent.com/25227022/212474906-39a5cf74-0f90-4638-b491-aa50447bd4a7.png)

- [x] The text on the mobile view is overlapped, kindly make sure to fix it so your page is appealing and the text is readable 

![Screenshot_20230114_144701](https://user-images.githubusercontent.com/25227022/212474990-f890b507-c4d3-4eb1-9b9c-d0955252ebd1.png)

2023-01-14 14:03 UTC, Ismailco commented on index.html
> +</section>
- [x] As the previous reviewer mentioned this section should include a header, a divider, and six individual articles, each with an image, title, subtitle, and description. Each article has two columns, the first with the image at the left and the second with the title, subtitle, and description, kindly consider adding a divider after the section header, and align the speakers properly in two columns in the desktop view

![Screenshot_20230114_145230](https://user-images.githubusercontent.com/25227022/212475241-43b89569-8e84-4aa8-a635-8ecdee46e14a.png)

2023-01-14 14:03 UTC, Ismailco commented on index.html
> +</button>
- [x] As the previous reviewer mentioned this button should not be displayed in the desktop view,
- [x] [OPTIONAL] also you should fix the `More Less` situation so only `More` is displayed when the list of speakers is not fully visible, and the `Less` should be used to hide the speakers

2023-01-14 14:03 UTC, Ismailco commented on index.html
> +    <div class="partner-title">Partner</div>
- [x] [OPTIONAL] Kindly make sure to add a divider after the `Partner` header, and make sure to use the same font size, weight, and colors so your design looks similar to the provided design

![Screenshot_20230114_145923](https://user-images.githubusercontent.com/25227022/212475521-ecf672ba-885c-4dcb-b686-7c7223274090.png)

2023-01-14 14:03 UTC, Ismailco commented on index.html
> +</section>
- [x] As the previous reviewer suggested: Please add the footer section for both pages the desktop version and the mobile version following the design guidelines to be similar to the original design, the footer in the desktop version for the home page is white background while the mobile version is a black background, besides in the mobile version the footer is on the about page with white background.

2023-01-14 14:03 UTC, Ismailco commented on about.html
> +    </section>
- [ ] Kindly  consider adding a background for the about page so your page follows the provided design


![](https://user-images.githubusercontent.com/25227022/212474493-b1871ba5-fe71-43f3-b2e3-1d1d649da8e3.png)

2023-01-14 19:48 UTC, Owusu-Desmond requested changes
Hi @Eldonratzlaff  :wave: 

You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 19:48 UTC, Owusu-Desmond commented on about.html
> +    </section>
- [ ] As requested by the previous code reviewers please make sure you add all sections of your page about the page, make it responsive, and apply the design to it. 
#### For now you have only this section :point_down: 
![Screenshot from 2023-01-14 17-07-20](https://user-images.githubusercontent.com/92303891/212486287-2fd6641f-3d6d-411d-a4af-d0afcf5a86ce.png)
#### You have to have all these sections as you can see below in your about page
![Screenshot from 2023-01-14 17-11-54](https://user-images.githubusercontent.com/92303891/212486678-d6bd5246-fd05-4186-be1c-12f8a195263d.png) ![Screenshot from 2023-01-14 17-12-13](https://user-images.githubusercontent.com/92303891/212486674-12da212b-fa05-4830-9d79-e2b4a72dd872.png)

2023-01-14 19:48 UTC, Owusu-Desmond commented on index.html
> +</section>
- [ ] While working on the changes the previous reviewer requested on this `Features Speakers` section please make sure that this section of your project matches the [preferred design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). Try giving some margins and adjusting the styles to match [the design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)

2023-01-14 21:16 UTC, Eldonratzlaff commented on about.html
> +    </section>
I don't understand what happens with the header because it works perfectly for me on my side

2023-01-14 21:41 UTC, codecaiine approved these changes
Hi @Eldonratzlaff , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linters errors :heavy_check_mark: 
- Website well deployed :heavy_check_mark: 

## Optional suggestions
- [ ] [OPTIONAL] I noticed that while you are implementing the different previous reviewer request changes. The changes affected your website design and user experience. Please take time and make sure to go through the design guideline and fix your design in order to make your website awesome and give a good user experience. :+1: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 21:42 UTC, merged